#!/usr/bin/env python3
"""Regenerate apworlds.csv from the community APWorld spreadsheet.

Strategy: the sheet's download links are rich-text hyperlinks (lost by the CSV export), so
we pull the XLSX export and scrape every github.com link from the worksheet relationships.
For each unique repo we ask the GitHub API for a release that ships a `.apworld` asset —
that presence check is the filter, so tracker/manager/client repos (no .apworld) drop out.

Per repo we prefer the floating `releases/latest/download/<asset>` URL when the asset is on
the latest release; otherwise we pin to the tag of the newest release that has one. Non-
github links (Discord/Drive/itch/...) can't be resolved automatically and are written to
apworlds.manual.txt for manual triage.

Needs a GitHub token for rate limits: `gh auth token` is used automatically if present.
Stdlib only. Run locally/CI, never at image build time.
"""
import argparse
import concurrent.futures
import io
import json
import os
import re
import subprocess
import sys
import urllib.request
import urllib.error
import zipfile
from collections import Counter

SHEET_ID = "1iuzDTOAvdoNe8Ne8i461qGNucg5OuEoF-Ikqs8aUQZw"
XLSX_URL = f"https://docs.google.com/spreadsheets/d/{SHEET_ID}/export?format=xlsx"
GH_LINK_RE = re.compile(r'Target="(https://github\.com/[^"]+)"')
REPO_RE = re.compile(r"https://github\.com/([^/]+)/([^/?#]+)")
# repos that appear in the sheet but aren't apworld sources
SKIP_REPOS = {"archipelagomw/archipelago"}

HEADER = """\
# Apworld manifest — downloaded into the generator image's custom_worlds/ at build time
# by scripts/fetch_apworlds.py (see Dockerfile.generator). No .apworld binaries are
# vendored in the repo.
#
# GENERATED by scripts/refresh_from_sheet.py from the community spreadsheet. Hand edits are
# allowed but will be overwritten on the next refresh; pin/override entries deliberately.
#
# Columns: name,url,sha256
#   DEFAULT = latest (releases/latest/download). To pin when an upstream release breaks,
#   swap the url to a tagged release and add its sha256.
name,url,sha256
"""


def gh_token():
    try:
        t = subprocess.run(["gh", "auth", "token"], capture_output=True, text=True).stdout.strip()
        return t or None
    except Exception:
        return None


TOKEN = gh_token()


def api(url):
    req = urllib.request.Request(url, headers={
        "User-Agent": "apworld-refresh",
        "Accept": "application/vnd.github+json",
    })
    if TOKEN:
        req.add_header("Authorization", f"Bearer {TOKEN}")
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)


def apworld_asset(release):
    for a in release.get("assets", []):
        if a["name"].lower().endswith(".apworld"):
            return a["name"], a.get("size", 0)
    return None


def resolve(repo):
    """Return (name, url, size_bytes) or None if no apworld release found."""
    owner, name = repo
    # 1) prefer the floating "latest" release
    try:
        latest = api(f"https://api.github.com/repos/{owner}/{name}/releases/latest")
        hit = apworld_asset(latest)
        if hit:
            asset, size = hit
            url = f"https://github.com/{owner}/{name}/releases/latest/download/{asset}"
            return (asset[:-len(".apworld")], url, size)
    except urllib.error.HTTPError as e:
        if e.code not in (404,):
            return None
    except Exception:
        return None
    # 2) fall back to the newest (pre)release that ships a .apworld; pin to its tag
    try:
        for rel in api(f"https://api.github.com/repos/{owner}/{name}/releases?per_page=15"):
            hit = apworld_asset(rel)
            if hit:
                asset, size = hit
                tag = rel["tag_name"]
                url = f"https://github.com/{owner}/{name}/releases/download/{tag}/{asset}"
                return (asset[:-len(".apworld")], url, size)
    except Exception:
        return None
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="apworlds.csv")
    ap.add_argument("--manual-out", default="apworlds.manual.txt")
    ap.add_argument("--workers", type=int, default=10)
    args = ap.parse_args()

    print(f"github auth: {'token' if TOKEN else 'ANONYMOUS (low rate limit!)'}")
    print("downloading xlsx export ...")
    with urllib.request.urlopen(XLSX_URL, timeout=60) as r:
        xbytes = r.read()
    zf = zipfile.ZipFile(io.BytesIO(xbytes))

    gh_links, all_links = set(), []
    for n in zf.namelist():
        if re.match(r"xl/worksheets/_rels/.*\.rels", n):
            text = zf.read(n).decode("utf-8")
            all_links += re.findall(r'Target="(https?://[^"]+)"', text)
            for link in GH_LINK_RE.findall(text):
                m = REPO_RE.match(link.replace("&amp;", "&"))
                if m:
                    repo = (m.group(1), m.group(2)[:-4] if m.group(2).endswith(".git") else m.group(2))
                    if f"{repo[0]}/{repo[1]}".lower() not in SKIP_REPOS:
                        gh_links.add(repo)
    repos = sorted(gh_links)
    print(f"unique github repos: {len(repos)}  (total links scraped: {len(all_links)})")

    resolved = {}
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.workers) as ex:
        for repo, res in zip(repos, ex.map(resolve, repos)):
            if res:
                name, url, size = res
                resolved[name] = (url, size)
                print(f"  OK  {repo[0]}/{repo[1]} -> {name} ({size//1024} KB)")

    # write manifest
    with open(args.out, "w") as f:
        f.write(HEADER)
        for name in sorted(resolved):
            url, _ = resolved[name]
            f.write(f"{name},{url},\n")

    # report non-github links for manual handling
    nongh = sorted({l for l in all_links if "github.com" not in l})
    with open(args.manual_out, "w") as f:
        f.write("# Non-GitHub links from the sheet — resolve/add these by hand if wanted.\n")
        for l in nongh:
            f.write(l + "\n")

    total_mb = sum(s for _, s in resolved.values()) / 1_048_576
    hosts = Counter(re.match(r"https?://([^/]+)", l).group(1) for l in nongh)
    print(f"\nwrote {len(resolved)} entries to {args.out}")
    print(f"estimated download/image size from these apworlds: {total_mb:.0f} MB")
    print(f"{len(nongh)} non-github links -> {args.manual_out} "
          f"(top hosts: {', '.join(h for h,_ in hosts.most_common(5))})")


if __name__ == "__main__":
    sys.exit(main())
